
import SupervisorLayout from "../../layouts/SupervisorLayout";

const SupervisorReports = () => {
  return (
    <SupervisorLayout>

      <h1 className="text-3xl font-bold mb-6">
        Reports Management
      </h1>

      {/* Summary Cards */}

      <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-6 mb-8">

        <div className="bg-blue-600 text-white p-5 rounded-xl shadow">

          <h3 className="text-lg">
            Total Labour
          </h3>

          <h1 className="text-4xl font-bold mt-2">
            35
          </h1>

        </div>

        <div className="bg-green-600 text-white p-5 rounded-xl shadow">

          <h3 className="text-lg">
            Present Today
          </h3>

          <h1 className="text-4xl font-bold mt-2">
            32
          </h1>

        </div>

        <div className="bg-purple-600 text-white p-5 rounded-xl shadow">

          <h3 className="text-lg">
            Today's Production
          </h3>

          <h1 className="text-4xl font-bold mt-2">
            450
          </h1>

        </div>

        <div className="bg-yellow-500 text-white p-5 rounded-xl shadow">

          <h3 className="text-lg">
            Monthly Earnings
          </h3>

          <h1 className="text-4xl font-bold mt-2">
            ₹12,500
          </h1>

        </div>

      </div>

      {/* Generate Report */}

      <div className="bg-white rounded-xl shadow p-5 mb-6">

        <h2 className="text-xl font-semibold mb-4">
          Generate Report
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-4 gap-4">

          <input
            type="date"
            className="border p-3 rounded-lg"
          />

          <input
            type="date"
            className="border p-3 rounded-lg"
          />

          <select className="border p-3 rounded-lg">

            <option>
              Select Report Type
            </option>

            <option>
              Attendance Report
            </option>

            <option>
              Production Report
            </option>

            <option>
              Labour Report
            </option>

          </select>

          <button className="bg-blue-700 text-white rounded-lg p-3">
            Generate Report
          </button>

        </div>

      </div>

      {/* Search */}

      <div className="bg-white rounded-xl shadow p-5 mb-6">

        <input
          type="text"
          placeholder="Search Reports..."
          className="w-full border p-3 rounded-lg"
        />

      </div>

      {/* Reports Table */}

      <div className="bg-white rounded-xl shadow p-5">

        <h2 className="text-xl font-semibold mb-4">
          Reports History
        </h2>

        <div className="overflow-x-auto">

          <table className="w-full">

            <thead>

              <tr className="border-b">

                <th className="p-3 text-left">
                  Report ID
                </th>

                <th className="p-3 text-left">
                  Report Type
                </th>

                <th className="p-3 text-left">
                  Generated By
                </th>

                <th className="p-3 text-left">
                  Date
                </th>

                <th className="p-3 text-left">
                  Status
                </th>

                <th className="p-3 text-left">
                  Action
                </th>

              </tr>

            </thead>

            <tbody>

              <tr className="border-b">

                <td className="p-3">
                  REP001
                </td>

                <td className="p-3">
                  Attendance Report
                </td>

                <td className="p-3">
                  Supervisor
                </td>

                <td className="p-3">
                  12-06-2026
                </td>

                <td className="p-3">

                  <span className="bg-green-100 text-green-700 px-3 py-1 rounded-full text-sm">
                    Completed
                  </span>

                </td>

                <td className="p-3">

                  <div className="flex gap-2">

                    <button className="bg-blue-600 text-white px-3 py-2 rounded-lg">
                      View
                    </button>

                    <button className="bg-green-600 text-white px-3 py-2 rounded-lg">
                      Download
                    </button>

                  </div>

                </td>

              </tr>

              <tr className="border-b">

                <td className="p-3">
                  REP002
                </td>

                <td className="p-3">
                  Production Report
                </td>

                <td className="p-3">
                  Supervisor
                </td>

                <td className="p-3">
                  13-06-2026
                </td>

                <td className="p-3">

                  <span className="bg-green-100 text-green-700 px-3 py-1 rounded-full text-sm">
                    Completed
                  </span>

                </td>

                <td className="p-3">

                  <div className="flex gap-2">

                    <button className="bg-blue-600 text-white px-3 py-2 rounded-lg">
                      View
                    </button>

                    <button className="bg-green-600 text-white px-3 py-2 rounded-lg">
                      Download
                    </button>

                  </div>

                </td>

              </tr>

              <tr>

                <td className="p-3">
                  REP003
                </td>

                <td className="p-3">
                  Labour Report
                </td>

                <td className="p-3">
                  Supervisor
                </td>

                <td className="p-3">
                  14-06-2026
                </td>

                <td className="p-3">

                  <span className="bg-yellow-100 text-yellow-700 px-3 py-1 rounded-full text-sm">
                    Pending
                  </span>

                </td>

                <td className="p-3">

                  <div className="flex gap-2">

                    <button className="bg-blue-600 text-white px-3 py-2 rounded-lg">
                      View
                    </button>

                    <button className="bg-green-600 text-white px-3 py-2 rounded-lg">
                      Download
                    </button>

                  </div>

                </td>

              </tr>

            </tbody>

          </table>

        </div>

      </div>

    </SupervisorLayout>
  );
};

export default SupervisorReports;